name: CI (minimum)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Markdown link check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check links in Markdown
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: "yes"
          config-file: ".github/workflows/.mlc-config.json"
          folder-path: "."

  secret-guard:
    name: Secrets guard (block committed secrets)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fail if secret-like files are tracked
        shell: bash
        run: |
          set -euo pipefail

          FAIL=0

          # 1) .env がコミットされていないか
          if git ls-files --error-unmatch ".env" >/dev/null 2>&1; then
            echo "::error::.env がリポジトリに含まれています。.env はコミットせず、.env.example を使ってください。"
            FAIL=1
          fi

          # 2) 鍵ファイルっぽいもの（*.key, *.pem, id_rsa など）
          TRACKED_KEYS=$(git ls-files "*.key" "*.pem" "id_rsa" "id_dsa" 2>/dev/null || true)
          if [[ -n "$TRACKED_KEYS" ]]; then
            echo "::error::鍵ファイルと思われるものがコミットされています:"
            echo "$TRACKED_KEYS"
            FAIL=1
          fi

          # 3) Webhookやトークンが含まれがちなファイル名
          TRACKED_SUS=$(git ls-files "*webhook*" "*token*" "*secret*" 2>/dev/null || true)
          if [[ -n "$TRACKED_SUS" ]]; then
            echo "::warning::注意: 機密情報を含む可能性のあるファイル名が見つかりました:"
            echo "$TRACKED_SUS"
            # warning 扱い。必要なら FAIL=1 に変更
          fi

          if [[ $FAIL -ne 0 ]]; then
            exit 1
          fi
